package models

// ParentChunk is a semantic block of text from a document. It holds the
// full unbroken context meant for LLM consumption.
type ParentChunk struct {
	ID string // UUID
	DocumentID string
	Content string
	TokenCount int
	Position int // 0-indexed ordinal within the document
}

// ChildChunk is a smaller, overlapping slice of a ParentChunk used for
// vector search. Each child holds an embedding generated by the embedding
// model.
type ChildChunk struct {
	ID string // UUID
	ParentID string
	Content string
	TokenCount int
	Position int // 0-indexed ordinal within the parent
	Embedding []float32
}

// Document represents an uploaded file. Status tracks the ingestion
// lifecycle.
type Document struct {
	ID string
	SourceName string
	SourceType string // "markdown", "pdf", "docx", "html", "text"
	Status string // "PENDING" | "INGESTING" | "READY" | "FAILED"
	ChunkCount int
	Error string
}

// Document status constants.
const (
	DocStatusPending = "PENDING"
	DocStatusIngesting = "INGESTING"
	DocStatusReady = "READY"
	DocStatusFailed = "FAILED"
)

// ValidDocumentStatus returns true if s is a known document status.
func ValidDocumentStatus(s string) bool {
	switch s {
	case DocStatusPending, DocStatusIngesting, DocStatusReady, DocStatusFailed:
		return true
	}
	return false
}
